/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      animation: {
        "slide-from-top": "slideFromTop 1s ease-out",
      },
      keyframes: {
        slideFromTop: {
          "0%": { transform: "translateY(-50px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
      },
      container: {
        center: true,
        screens: {
          xsm: "100%",
          xm: "100%",
          xlg: "100%",
          sm: "100%",
          md: "100%",
          tab: "100%",
          lg: "1024px",
          xl: "1245px",
        },
        padding: {
          DEFAULT: "1rem",
          xl: "0rem",
        },
      },
      colors: {
        primary: "#EF3B69",
        secondary: "#3C7CC8",
        gray: "#707978",
        darkGray:"#676767",
        yellow:"#FBD603",
        yellowDark:"#d5b500",
        light: "#F9F9F9",
        lightGray:"#F8F8F8",
        "black-dim": "#23282d",
        "black-dark": "#A9AEB4",
        "black-light": "#7E7E7E",
        link: "#2C77AC",
        "white-light": "#EAEAEA",
        'light-shade':"#EEEEEE",
        skeleton: "#E0E0E0",
        "skeleton-white": "#F0F0F0",
      },
      fontSize: {
        "8xl": "8px",
        xsm: "10px",
        "15xl": "15px",
        "18xl": "18px",
        "22xl": "22px",
        "26xl": "26px",
        "45xl": "45px",
        "80xl": "80px",
      },
      borderRadius: {
        "5px": "5px",
        "15px": "15px",
      },
      fontFamily: {
        inter: ["Inter", "sans-serif"],
      },
      screens: {
        xsm: "320px",
        xm: "390px",
        xlg: "425px",
        sm: "640px",
        md: "768px",
        tab: "992px",
        lg: "1024px",
        xl: "1245px",
      },
      spacing: {
        "1px": "1px",
        "2px": "2px",
        "3px": "3px",
        "15px": "15px",
        "17px": "17px",
        "18px": "18px",
        "19px": "19px",
        "25px": "25px",
        "30px": "30px",
        "34px": "34px",
        "50px": "50px",
        "59px": "59px",
        "60px": "60px",
        "62px": "62px",
        "72px": "72px",
        "82px": "82px",
        "86px": "86px",
        "114px": "114px",
        "120px": "120px",
        "150px": "150px",
        "200px": "200px",
        "274px": "274px",
        "309px": "309px",
      },
      gap: {
        "19px": "19px",
      },
      backgroundImage: {
        // "footer-background": "url('/src/assets/images/footer-bg.png')",
        // "campaign-background": "url('/src/assets/images/campaign_bg_cover.jpg')",
        // "campaign-page-background-sm": "url('/src/assets/images/campaign-bg-sm.jpg')",
        // "deals-background": "url('https://i.ibb.co/1Rc430n/Group-48695.jpg')",
        // "deals-background-sm": "url('/src/assets/images/dealOfTheWeekBG.jpg')",
      },
      boxShadow: {
        "3xl": "0 0 0 1px rgb(230, 230, 230)",
        card: "rgba(99, 99, 99, 0.2) 0px 2px 8px 0px",
      },
      dropShadow: {
        "3xl": "1px 5px 2px rgba(0, 0, 0, 0.25)",
        "2xl": "0px 5px 2px rgba(0, 0, 0, 0.15)",
      },
      height: {
        'screen-minus-100': 'calc(100vh - 100px)',
      },
    },
  },
  plugins: [],
}